apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-msa-ingress
  namespace: default
spec:
  rules:
    - host: petclinic.msa.local
      http:
        paths:
           - path: "/"
             pathType: Prefix
             backend:
               service:
                 name: gateway
                 port:
                   number: 8080
               
