apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
spec:
  selector:
    matchLabels:
      app: visits
  replicas: 1
  template:
    metadata:
      labels:
        app: visits
    spec:
      containers:
        - name: visits
          image: youngpig/spring-petclinic-visits-service:1.0.0.RELEASE
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1024Mi"
              cpu: "1"
          env:
            - name: JAVA_OPTS
              value: "-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: DATASOURCE_URL
              value: jdbc:mysql://mysql/petclinic
            - name: DATASOURCE_USERNAME
              value: root
            - name: DATASOURCE_PASSWORD
              value: petclinic
            - name: DATASOURCE_INIT_MODE
              value: always
---
apiVersion: v1
kind: Service
metadata:
  name: visits
  labels:
    svc: visits
spec:
  selector:
    app: visits
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
