apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: petclinic_customers
  namespace: default
spec:
  components:
  - name: petclinic_customers
    properties:
      objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: customers
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: customers
          template:
            metadata:
              labels:
                app: customers
            spec:
              containers:
              - env:
                - name: JAVA_OPTS
                  value: -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError
                - name: SERVER_PORT
                  value: "8080"
                - name: SPRING_PROFILES_ACTIVE
                  value: mysql
                - name: DATASOURCE_URL
                  value: jdbc:mysql://mysql/petclinic
                - name: DATASOURCE_USERNAME
                  value: root
                - name: DATASOURCE_PASSWORD
                  value: petclinic
                - name: DATASOURCE_INIT_MODE
                  value: always
                image: youngpig/spring-petclinic-customers-service:1.0.0.RELEASE
                name: customers
                readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 200m
                    memory: 128Mi
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: vets
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: vets
          template:
            metadata:
              labels:
                app: vets
            spec:
              containers:
              - env:
                - name: JAVA_OPTS
                  value: -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError
                - name: SERVER_PORT
                  value: "8080"
                - name: SPRING_PROFILES_ACTIVE
                  value: mysql
                - name: DATASOURCE_URL
                  value: jdbc:mysql://mysql/petclinic
                - name: DATASOURCE_USERNAME
                  value: root
                - name: DATASOURCE_PASSWORD
                  value: petclinic
                - name: DATASOURCE_INIT_MODE
                  value: always
                image: youngpig/spring-petclinic-vets-service:1.0.0.RELEASE
                name: vets
                readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 200m
                    memory: 128Mi
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: visits
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: visits
          template:
            metadata:
              labels:
                app: visits
            spec:
              containers:
              - env:
                - name: JAVA_OPTS
                  value: -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError
                - name: SERVER_PORT
                  value: "8080"
                - name: SPRING_PROFILES_ACTIVE
                  value: mysql
                - name: DATASOURCE_URL
                  value: jdbc:mysql://mysql/petclinic
                - name: DATASOURCE_USERNAME
                  value: root
                - name: DATASOURCE_PASSWORD
                  value: petclinic
                - name: DATASOURCE_INIT_MODE
                  value: always
                image: youngpig/spring-petclinic-visits-service:1.0.0.RELEASE
                name: visits
                readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 200m
                    memory: 128Mi
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: gateway
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: gateway
          template:
            metadata:
              labels:
                app: gateway
            spec:
              containers:
              - env:
                - name: JAVA_OPTS
                  value: -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError
                - name: SERVER_PORT
                  value: "8080"
                - name: SPRING_PROFILES_ACTIVE
                  value: mysql
                - name: DATASOURCE_URL
                  value: jdbc:mysql://mysql/petclinic
                - name: DATASOURCE_USERNAME
                  value: root
                - name: DATASOURCE_PASSWORD
                  value: petclinic
                - name: DATASOURCE_INIT_MODE
                  value: always
                image: youngpig/spring-petclinic-cloud-gateway:1.0.0.RELEASE
                name: gateway
                readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 200m
                    memory: 128Mi
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: web
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: web
          template:
            metadata:
              labels:
                app: web
            spec:
              containers:
              - env:
                - name: JAVA_OPTS
                  value: -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError
                - name: SERVER_PORT
                  value: "8080"
                - name: SPRING_PROFILES_ACTIVE
                  value: mysql
                - name: DATASOURCE_URL
                  value: jdbc:mysql://mysql/petclinic
                - name: DATASOURCE_USERNAME
                  value: root
                - name: DATASOURCE_PASSWORD
                  value: petclinic
                - name: DATASOURCE_INIT_MODE
                  value: always
                image: youngpig/spring-petclinic-web-app:1.0.0.RELEASE
                name: web
                readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: 8080
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 200m
                    memory: 128Mi
      - apiVersion: v1
        kind: Service
        metadata:
          labels:
            svc: customers
          name: customers
        spec:
          ports:
          - name: http
            port: 8080
            targetPort: 8080
          selector:
            app: customers
          type: ClusterIP
      - apiVersion: v1
        kind: Service
        metadata:
          labels:
            svc: vets
          name: vets
        spec:
          ports:
          - name: http
            port: 8080
            targetPort: 8080
          selector:
            app: vets
          type: ClusterIP
      - apiVersion: v1
        kind: Service
        metadata:
          name: gateway
          labels:
            svc: gateway
        spec:
          selector:
            app: gateway
          ports:
            - name: http
              port: 8080
              targetPort: 8080
              nodePort: 31080
          type: NodePort
      - apiVersion: v1
        kind: Service
        metadata:
          labels:
            svc: visits
          name: visits
        spec:
          ports:
          - name: http
            port: 8080
            targetPort: 8080
          selector:
            app: visits
          type: ClusterIP
      - apiVersion: v1
        kind: Service
        metadata:
          labels:
            svc: web
          name: web
        spec:
          ports:
          - name: http
            port: 8080
            targetPort: 8080
          selector:
            app: web
          type: ClusterIP
    type: k8s-objects
  policies:
  - name: topology-default
    type: topology
    properties:
      clusters: ['k8s-master']
      namespace: default
  workflow:
    steps:
    - name: deploy2default
      properties:
        policies: ['topology-default']
      type: deploy
